version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rashtratimes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  minio:
    image: minio/minio:latest
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/rashtratimes?schema=public
      JWT_SECRET: supersecretjwtstringthatissolong
      REDIS_URL: redis://redis:6379
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      NEXT_PUBLIC_API_URL: http://localhost:3333
    depends_on:
      - postgres
      - redis
    ports:
      - '3333:3333'
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
    ports:
      - '3000:3000'
    depends_on:
      - api
volumes:
  postgres-data:
  minio-data:
