name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: |
          # No lockfile is committed yet, so allow pnpm to resolve dependencies dynamically.
          pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Deploy Web to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          pnpm dlx vercel deploy --prod --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID"
      - name: Deploy API to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL=~/.fly
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          fly deploy --remote-only
      - name: Smoke check
        run: |
          curl -f ${{ secrets.API_HEALTH_URL }}/health
